# action.yml
name: "Auto-PR Submodules Updates"
description: "Automatically open (or update) a pull-request when it detects updates to individual submodule in a repository."
inputs:
  token:
    description: "Github token with access to the owner repository."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
